# Generated by Django 3.2.6 on 2021-08-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the business.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The title/role of a type of employee.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('businesses', models.ManyToManyField(to='exercise.Business')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the vehicle.', max_length=50)),
                ('fuel_capacity', models.IntegerField(default=0, help_text='The total fuel capacity in gallons.')),
                ('burn_rate', models.FloatField(default=0, help_text='The burn rate of fuel in gal/h.')),
                ('weight', models.FloatField(default=0, help_text='The weight of the vehicle in pounds.')),
            ],
        ),
        migrations.CreateModel(
            name='TripVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.business')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripEmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.business')),
                ('employee_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.employeetype')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='employee_types',
            field=models.ManyToManyField(through='exercise.TripEmployeeType', to='exercise.EmployeeType'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicles',
            field=models.ManyToManyField(through='exercise.TripVehicle', to='exercise.Vehicle'),
        ),
    ]
