# Generated by Django 3.2.6 on 2021-08-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='combatload',
            name='ammoitem',
        ),
        migrations.AddField(
            model_name='combatload',
            name='ammo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ammo'),
        ),
        migrations.AddField(
            model_name='combatload',
            name='base_allocation',
            field=models.PositiveIntegerField(default=0, help_text='The base combat load for this weapon and ammo combination.'),
        ),
        migrations.AddField(
            model_name='combatload',
            name='daily_assault',
            field=models.PositiveIntegerField(default=0, help_text='The daily sustainment quantity.'),
        ),
        migrations.AddField(
            model_name='combatload',
            name='daily_sustain',
            field=models.PositiveIntegerField(default=0, help_text='The daily sustainment quantity.'),
        ),
        migrations.AddField(
            model_name='combatload',
            name='unit_type',
            field=models.CharField(choices=[('G', 'Ground Combat Element'), ('N', 'Non-Ground Combat Element')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='exerciseedl',
            name='phasing_location',
            field=models.CharField(choices=[('AE', 'Assault Element'), ('AFOE', 'Assault Follow-On Element')], default='AE', help_text='The location of the item in relation to the phasing.', max_length=4),
        ),
        migrations.AddField(
            model_name='exerciseedl',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The quantity of an item.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='combat_loads',
            field=models.ManyToManyField(help_text='A list of equipment ammo that this equipment contains.', through='exercise.CombatLoad', to='exercise.Ammo'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipments',
            field=models.ManyToManyField(through='exercise.ExerciseEdl', to='exercise.Equipment'),
        ),
        migrations.AlterField(
            model_name='exerciseedl',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.equipment'),
        ),
        migrations.DeleteModel(
            name='AmmoItem',
        ),
        migrations.DeleteModel(
            name='EquipmentItem',
        ),
    ]
