# Generated by Django 3.2.6 on 2021-08-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseEquipmentItems',
            new_name='ExerciseEquipmentItem',
        ),
        migrations.DeleteModel(
            name='EquipmentAmmoItem',
        ),
    ]
