# Generated by Django 3.2.6 on 2021-08-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the part.', max_length=50)),
                ('weight', models.IntegerField(default=0, help_text='The weight of the part.')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.part')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parts',
            field=models.ManyToManyField(help_text='A list of vehicle parts that this vehicle contains.', through='exercise.VehiclePart', to='exercise.Part'),
        ),
    ]
