# Generated by Django 3.2.6 on 2021-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExercisePerson',
            new_name='ExercisePeopleTypes',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='PeopleTypes',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='unites',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='exercisepeopletypes',
            old_name='person_types',
            new_name='people_types',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='persons',
        ),
        migrations.AddField(
            model_name='exercise',
            name='people_types',
            field=models.ManyToManyField(through='exercise.ExercisePeopleTypes', to='exercise.PeopleTypes'),
        ),
    ]
