# Generated by Django 3.2.6 on 2021-08-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20210806_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExercisePeopleTypes',
            new_name='ExercisePeopleType',
        ),
        migrations.RenameModel(
            old_name='PeopleTypes',
            new_name='PeopleType',
        ),
        migrations.RenameField(
            model_name='exercisepeopletype',
            old_name='people_types',
            new_name='people_type',
        ),
    ]
