# Generated by Django 3.2.6 on 2021-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20210808_1051'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipmentammo',
            constraint=models.UniqueConstraint(fields=('equipment', 'ammo', 'unit_type'), name='EQUIPMENT_AMMO_UNIQUE'),
        ),
    ]
